version: '3.8'
services:
  proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - red_interna
    depends_on:
      - web1
      - web2

  web1:
    image: nginx:latest
    networks:
      - red_interna
    volumes:
      - contenido_web:/usr/share/nginx/html

  web2:
    image: nginx:latest
    networks:
      - red_interna
    volumes:
      - contenido_web:/usr/share/nginx/html

networks:
  red_interna:
    driver: bridge

volumes:
  contenido_web:
